name: Build and push docker image
on:
  push:
    branches: [ "docker-build" ]
  pull_request:
    branches: [ "docker-build" ]
jobs:
  push_to_registry:
    name: Deploy to development
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install yq
        uses: chrisdickinson/setup-yq@latest
        with:  
          yq-version: "v4.27.5"
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: tanawatchans/web-app:development-${{ steps.commit_hash.outputs.sha_short }}

      - name: Add image tag to development helm value
        run: yq -i '.deployment.image = "tanawatchans/web-app:development-${{ steps.commit_hash.outputs.sha_short }}"' helm-values/development.yaml

      - name: Deploy to development
        run: echo deploying && cat helm-values/development.yaml
