name: Build and push docker image
on:
  push:
    branches: [ "development" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: gke-cluster
  GKE_ZONE: asia-southeast1-c
  DEPLOYMENT_NAME: web-app

jobs:
  push_to_registry:
    name: Deploy to development
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      
      # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
      - name: Authenticate to GKE
        run: |-
          gcloud --quiet auth configure-docker
      
      # Get the GKE credentials for deploying to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Install yq
        uses: chrisdickinson/setup-yq@latest
        with:  
          yq-version: "v4.27.5"
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short hand commit hash
        id: commit_hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      - name: Build and push Docker image to Docker hub
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: tanawatchans/${{ env.DEPLOYMENT_NAME }}:development-${{ steps.commit_hash.outputs.sha_short }}

      - name: Add image tag to development helm value
        run: yq -i '.deployment.image = "tanawatchans/${{ env.DEPLOYMENT_NAME }}:development-${{ steps.commit_hash.outputs.sha_short }}"' helm-values/development.yaml

      - name: Deploy to development using helm
        run: |-
          helm upgrade --install ${{ env.DEPLOYMENT_NAME }} ./helm-templates -f helm-values/development.yaml
